version: "3"
services:
    node:
        image: terrybui/node-cache-me-outside:1.0.0 
        ports:
         - "3000:3000"
        depends_on:
         - redis
    redis:
        image: redis
        command: redis-server --appendonly yes
        volumes:
         - redis-data:/data

volumes:
    redis-data:
