version: "3"
services:
    node:
        build: .
        ports:
         - "3000:3000"
        depends_on:
         - redis
    redis:
        image: redis
        command: redis-server --appendonly yes